version : '3'

services: 
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "musjib"
            MONGO_INITDB_ROOT_PASSWORD: "123456"
        networks:
            - narrnet
        
    
    authapi:
        image: uzlash/narr-gateway:v1.0
        restart: always
        ports: 
            - "3000:3000"
        environment:
            MONGOHOST: "mongo"
            MONGOUSER: "musjib"
            MONGOPASS: "123456"
            MONGODB: "narrdb"
        networks: 
            - narrnet
        depends_on:
            - mongo
        

networks:
    narrnet:
        driver: bridge