version : '3'

services: 
    mongo:
        image: mongo
        ports:
            - "27020:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "musjib"
            MONGO_INITDB_ROOT_PASSWORD: "123456"
            
        volumes: 
            - /Users/lectro/Documents/devSpace/server/node/narr/storage:/data/db
        networks:
            - narrnet
        
    redisDB:
        image: redis
        ports: 
            - "6379:6379"
        networks:
            - narrnet
    
    narrapi:
        image: shamskhalil/narr-api:v1.5.8
        restart: always
        ports: 
            - "3000:3000"
        environment:
            MONGOHOST: "mongo"
            MONGOUSER: "musjib"
            MONGOPASS: "123456"
            MONGODB: "narrdb"
        networks: 
            - narrnet
        depends_on:
            - mongo
            - redisDB
        

networks:
    narrnet:
        driver: bridge