name: narr
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  http: ^0.12.2
  dio: ^3.0.10
  flutter_inappwebview: ^4.0.0+4
  connectivity: ^2.0.0
  permission_handler: ^4.2.0+hotfix.3
  socket_io_client: ^0.9.12


  # front end package
  cupertino_icons: ^0.1.3
  photo_view: ^0.10.3
  # path_provider: ^1.6.24
  ext_storage: ^1.0.3
  charts_flutter: ^0.9.0
  file_picker: 2.0.0
  image_picker: ^0.6.7+14
  font_awesome_flutter: ^8.10.0
  carousel_slider: ^2.3.1
  numberpicker: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
